# Generated by Django 6.0.1 on 2026-01-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_no', models.CharField(db_column='accountno', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('balance', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
